# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sample template to create a work environment project for datathon team or
# similar. This template
#   - creates a data hosting project and audit logs project.
#   - creates a team project with:
#       - 2 VMs, one with a custom image from GCS, and other with a standard
#         Ubuntu image.
#       - a firewall rule to enable RStudio.
#       - BigQuery and Google Cloud Storage services for holding team data
#
# Usage:
# 1) Replace all fields with relevant values in (a copy of) this file.
# 2) Run gcloud init
# 3) run ./create_project.py --project_yaml=${NEW_PROJECT_YAML?}
# 4) When prompted, follow the steps to set up a Stackdriver account.

overall:
  organization_id: '12345678'
  folder_id: '98765321'
  billing_account: 000000-000000-000000

# Configure the audit logs hosting project here.
audit_logs_project:
  project_id: my-audit-logs
  owners_group: my-audit-logs-owners@mydomain.com
  auditors_group: some-auditors-group@mydomain.com
  audit_logs:
    logs_bq_dataset:
      properties:
        location: US
        name: audit_logs
  stackdriver_alert_email: some-alerts-group@mydomain.com

# Multiple team projects can be deployed at once with the one YAML file.
projects:
- project_id: my-data-project  # Data-hosting project.
  owners_group: my-data-project-owners@my-domain.com
  auditors_group: some-auditors-group@my-domain.com
  data_readwrite_groups:
  - some-readwrite-group@my-domain.com
  data_readonly_groups:
  - some-readonly-group@my-domain.com
  - another-readonly-group@googlegroups.com
  create_deletion_lien: true
  stackdriver_alert_email: some-alerts-group@my-domain.com
  audit_logs:
    logs_gcs_bucket:
      properties:
        # For naming recommendations, see https://cloud.google.com/storage/docs/best-practices.
        name: logs-hash-of-my-data-project
        location: ASIA-SOUTHEAST1
        storageClass: REGIONAL
      ttl_days: 365
    logs_bq_dataset:
      properties:
        # Naming convention: PROJECT_ID, with underscores instead of dashes.
        name: my_data_project
        location: US
  resources:
    bq_datasets:
    - properties:
        name: us_data
        location: US
    gcs_buckets:
    - properties:
        location: ASIA-SOUTHEAST1
        name: data-bucket
        storageClass: REGIONAL
- project_id: my-team-project  # Team project.
  owners_group: my-team-project-owners@my-domain.com
  auditors_group: some-auditors-group@my-domain.com
  data_readwrite_groups:
  - my-team-project-users@my-domain.com
  # Open port 8787 as required by RStudio server.
  enabled_apis:
  - bigquery-json.googleapis.com  # BigQuery
  - compute.googleapis.com        # Google Compute Engine
  - ml.googleapis.com             # Cloud Machine Learning Engine
  # If alert email is present, create StackDriver alerts.
  stackdriver_alert_email: some-alerts-group@my-domain.com
  audit_logs:
    logs_gcs_bucket:
      # For naming recommendations, see https://cloud.google.com/storage/docs/best-practices.
      properties:
        name: logs-hash-of-my-team-project
        location: US
        storageClass: MULTI_REGIONAL
      ttl_days: 365
    logs_bq_dataset:
      properties:
        # Naming convention: PROJECT_ID, with underscores instead of dashes.
        name: my_team_project
        location: US
  resources:
    gcs_buckets:
    - properties:
        location: ASIA-SOUTHEAST1
        name: my-team-project-shared-files
        storageClass: REGIONAL
    gce_firewalls:
    - properties:
        name: allow-rstudio
        rules:
        - IPProtocol: tcp
          ports:
          - '8787'
        sourceRanges:
        - '0.0.0.0/0'
    gce_instances:
    - properties:
        name: work-machine-1
        zone: asia-southeast1-a
        machineType: n1-standard-1
        diskImage: projects/debian-cloud/global/images/family/debian-9
        network: default
    # Warning: Avoid additional_project_permissions for data hosting projects.
    iam_policies:
    - name: additional_project_permissions
      properties:
        roles:
        - role: roles/viewer
          members:
          - group:my-team-project-users@my-domain.com
        - role: roles/bigquery.user
          members:
          - group:my-team-project-users@my-domain.com
        - role: roles/storage.objectCreator
          members:
          - group:my-team-project-users@my-domain.com
        - role: roles/storage.objectViewer
          members:
          - group:my-team-project-users@my-domain.com
        - role: roles/ml.developer
          members:
          - group:my-team-project-users@my-domain.com
