# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sample template to create three projects: a project for hosting audit-logs
# and two projects for hosting data. The data hosting projects have GCS buckets,
# BigQuery datasets, logging to GCS and BigQuery, and logs-based metrics for
# unexpected access.

# Actually, this config is equivalent to ../project_with_remote_audit_logs.yaml,
# but is split into 4 separate files for readability.

# This is the file that should be passed in to the script. Actually, it is OK to
# use any file as the root to pass in to the script if the "import_files"
# organises a tree which connects all the files included.

import_files: [
  'partial_audit.yaml',
  'partial_projects.yaml',
  'partial_other_projects.yaml',
]

overall:
  organization_id: '12345678'           # Replace this with your Organization ID, or remove to setup without an organization.
  folder_id: '98765321'                 # Optional. Replace this with an existing folder within the organization.
  billing_account: 000000-000000-000000 # Replace this with your Billing Account.
  domain: 'domain.com'                  # Replace this with your domain.
